language: python
dist: xenial

python:
 - "2.7"
 - "3.7"
 - "3.8"

os:
 - "linux"

sudo: required

services:
  - docker
  - mongodb

before_install:
- docker pull phusion/baseimage:0.9.19
- sudo yes | sudo apt-get install libpcap-dev libnet-dev tshark

script:
 - sudo service docker restart
 - sudo docker info
 - sudo pip install -r requirements.txt
 - sudo pip install -r requirements-dev.txt # only for development env
 - sleep 15 # wait for mongodb
 - sudo python ohp.py -m all --test
 - pytest

after_success:
 - codecov
