version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: "elasticsearch"
    environment:
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - discovery.type=single-node
      - xpack.security.enabled=false # note: you must secure your elasticsearch otherwise everyone can access it
                                     # you also need to add the credentials to config.py
    ports:
      - 9200:9200
    volumes:
      - ./data/db:/usr/share/elasticsearch/data:Z

  ohp:
    build:
      context: .
      dockerfile: "Dockerfile.api"
    command: bash -c "sleep 30 && python3 ohp.py --start-api-server"
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_DOCKER_ENV=true
    ports:
      - 5000:5000
    volumes:
      - .:/OWASP-Honeypot
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:latest-ubuntu
    container_name: "grafana"
    volumes:
      - ./data/grafana:/var/lib/grafana:Z
    ports:
      - 3000:3000
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
