version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: "elasticsearch"
    environment:
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./data/db:/usr/share/elasticsearch/data

  ohp:
    build:
      context: .
      dockerfile: "Dockerfile.api"
    command: bash -c "sleep 30 && python3 ohp.py --start-api-server"
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_DOCKER_ENV=true
    ports:
      - 5000:5000
    volumes:
      - .:/OWASP-Honeypot
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
